# https://www.consul.io/docs/index.html
# https://hub.docker.com/_/consul

# https://blog.csdn.net/taotoxht/article/details/82823816
# docker network create --subnet=172.28.0.0/24 consul
# docker run -d  --name consul_s1 --net staticnet  --ip 172.18.0.2   -v /opt/config/consul/consul_server_config/basic_config_1.json:/consul/config/basic_config_1.json  consul agent -config-dir /consul/config

version: "3.1"
networks:
  default:
    external:
      # 172.19.0.0/16
      name: docker_default
services:
  s1:
    image: consul
    networks: 
      default:
        ipv4_address: 172.19.1.2
    volumes:
      - ./s1.json:/consul/config/s1.json
    command: agent -config-dir /consul/config
  s2:
    image: consul
    networks: 
      default:
        ipv4_address: 172.19.1.3
    volumes:
      - ./s2.json:/consul/config/s2.json
    command: agent -config-dir /consul/config
  s3:
    image: consul
    networks: 
      default:
        ipv4_address: 172.19.1.4
    volumes:
      - ./s3.json:/consul/config/s3.json
    command: agent -config-dir /consul/config
  c1:
    image: consul
    networks: 
      default:
        ipv4_address: 172.19.1.5
    ports:
      - "8500:8500"
    volumes:
      - ./c1.json:/consul/config/c1.json
    command: agent -config-dir /consul/config
