apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nsqadmin
  name: nsqadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nsqadmin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: nsqadmin
    spec:
      containers:
      - args:
        - /nsqadmin
        - --lookupd-http-address=nsqlookupd:4161
        image: nsqio/nsq
        imagePullPolicy: ""
        name: nsqadmin
        ports:
        - containerPort: 4171
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
