apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nsqd
  name: nsqd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nsqd
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: nsqd
    spec:
      containers:
      - args:
        - /nsqd
        - --lookupd-tcp-address=nsqlookupd:4160
        image: nsqio/nsq
        imagePullPolicy: ""
        name: nsqd
        ports:
        - containerPort: 4150
        - containerPort: 4151
        resources: {}
      hostname: nsqd
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
