apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nsqlookupd
  name: nsqlookupd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nsqlookupd
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: nsqlookupd
    spec:
      containers:
      - args:
        - /nsqlookupd
        image: nsqio/nsq
        imagePullPolicy: ""
        name: nsqlookupd
        ports:
        - containerPort: 4160
        - containerPort: 4161
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
